metering.server.url=http://localhost:5555/invoke/wmDemo.utils.metering/capture
metering.accumulation.period=10
metering.report.period=20

# metering.proxy.type=DIRECT
# metering.proxy.address=

# By default, HTTP basic authentication is disabled in JVM runtimes for security reasons.
# To use proxy authentication, you must enable basic authentication by adding the following line
# in the custom_wrapper.conf file of each product that uses Software AG Metering:
# wrapper.java.additional.777=-Djdk.http.auth.tunneling.disabledSchemes=""
# metering.proxy.user=
# metering.proxy.pass=