services:
  msr:
    image: ${PSM_DEV_CONTAINER_IMAGE}:${PSM_DEV_CONTAINER_TAG}
    container_name: 5s-psm-01-dev02-msr
    volumes:
      - ${PSM_HOST_MSR_LICENSE_FILE_LOCATION}:${PSM_GUEST_MOUNT_POINT_LICENSE_FILE}
      - ./config/MSR/application.properties:${PSM_GUEST_MOUNT_POINT_APPLICATION_PROPERTIES}
      ## Our code
      - ../../01.code/is-packages/Canonicals/:${PSM_GUEST_PACKAGES_FOLDER}/Canonicals/
      - ../../01.code/is-packages/PublisherExample/:${PSM_GUEST_PACKAGES_FOLDER}/PublisherExample/
      - ../../01.code/is-packages/ServiceMockup/:${PSM_GUEST_PACKAGES_FOLDER}/ServiceMockup/
      - ../../01.code/is-packages/ServiceMockupLocalTest/:${PSM_GUEST_PACKAGES_FOLDER}/ServiceMockupLocalTest/
      - ../../01.code/is-packages/SubscriberExample/:${PSM_GUEST_PACKAGES_FOLDER}/SubscriberExample/
      - ../../01.code/is-packages/WxAssert/:${PSM_GUEST_PACKAGES_FOLDER}/WxAssert/
      - ../../01.code/is-packages/WxAssertTest/:${PSM_GUEST_PACKAGES_FOLDER}/WxAssertTest/
      - ../../01.code/is-packages/WxIsTestTools/:${PSM_GUEST_PACKAGES_FOLDER}/WxIsTestTools/
      - ../../01.code/is-packages/WxIsTestToolsLocalTest/:${PSM_GUEST_PACKAGES_FOLDER}/WxIsTestToolsLocalTest/
      - ../../01.code/is-packages/WxTestDataGen/:${PSM_GUEST_PACKAGES_FOLDER}/WxTestDataGen/
    environment:
      # TODO: check SAG_ variable names after IBM's acquisition
      - SAG_IS_LICENSE_FILE=${PSM_GUEST_MOUNT_POINT_LICENSE_FILE}
      - SAG_IS_CONFIG_PROPERTIES=${PSM_GUEST_MOUNT_POINT_APPLICATION_PROPERTIES}
    ports:
      - ${WMDF_PORT_PREFIX}55:5555
    depends_on:
      um:
        condition: service_healthy
  um:
    image: ${PSM_DEV_UM_CONTAINER_IMAGE}:${PSM_DEV_UM_CONTAINER_TAG}
    container_name: 5s-psm-01-dev02-um
    volumes:
      - um_data:${PSM_GUEST_MOUNT_POINT_UM_REALM_DATA}
      - ./config/UM/Licence/:${PSM_GUEST_MOUNT_POINT_UM_REALM_LICENSE_FOLDER}
      - um_logs:${PSM_GUEST_MOUNT_POINT_UM_REALM_LOGS}
      - um_users:${PSM_GUEST_MOUNT_POINT_UM_REALM_USERS}
    ports:
      - ${WMDF_PORT_PREFIX}90:9000
    environment:
      - REALM_NAME=umdev02

volumes:
  um_data: {}
  um_logs: {}
  um_users: {}